
GET http://localhost:3000/estudiantes
###
POST http://localhost:3000/estudiantes/agregar
Content-Type: application/json

{  
    "codigo":1,
    "nombre": "Juan",
    "apellido": "Pérez",
    "tipo_documento": "CC",
    "numero_documento": "123456789",
    "estado": "1",
    "genero": "M"
}
###
GET http://localhost:3000/materias

###
POST http://localhost:3000/materias/agregar
Content-Type: application/json

{  
    "codigo":168,
    "nombre": "Sistemass bd",
    "cupos": 8,
    "estado": "b"
}

###
GET http://localhost:3000/inscripciones

###
POST http://localhost:3000/inscripciones/agregar
Content-Type: application/json

{
    "id_inscripcion" : 1,
    "codigo_estudiante"  : 1,
    "codigo_materia" : 1,"
    "fecha_inscripcion": "2020-05-05T16:34:44.719+03:00"
}