
GET http://localhost:3000
###
POST http://localhost:3000/estudiantes
content-type: application/json

{
   "codigo":1,
    "nombre":"Juan",
    "apellido":"Pérez",
    "tipo_documento":"CC",
    "numero_documento":123456,
    "estado":1,
    "genero":"M"
 
}